```{r include = FALSE}
require(rmarkdown); require(knitr); require(sevenbridges); require(readr)

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("~/sbg_auth.R")

```

<hr>



## base command

```{sh base command, eval=FALSE}

compareBamGenotypes.pl \
-o /datastore/output/$NAME_WT/genotyped \
-nb $BAM_WT_TMP \
-j /datastore/output/$NAME_WT/genotyped/result.json \
-tb $BAM_MT_TMP \

```

<br><br><br><br>

## docker 

The docker conatiner is

``` cgrlab/cgpbox_dev:develop ```

## arguments

```{r arguments, eval=run.mode=="skip"}
arguments = list(
  
input(id = "bam", label = "bam", description = "either wildtype or tumour bam", type = "File", prefix = "-i")

)

```

## App ports {.tabset .tabset-fade .tabset-tabs}

### Inputs

```{r inputs, eval=run.mode=="push"}
inputs = list(
  
input(id = "normal_bam", label = "normal_bam", description = "normal wildtype bam", type = "File", prefix = "-nb", stageInput = "link", secondaryFiles = list(".bai")),
  
input(id = "tumour_bam", label = "tumour_bam", description = "mutant tumour bam", type = "File", prefix = "-tb", stageInput = "link", secondaryFiles = list(".bai"))
  
)

```

### Outputs

```{r output, eval = run.mode=="push"}

outputs = list(

output(id = "std_out", label = "std_out", 
description = "standard output", type = "File...",
metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"*.{out}\"")),
  
output(id = "result", label = "genotype comparison", 
description = "genotype comarison results", type = "File...",
inheritMetadataFrom = "#tumour_bam", metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"genotype_check/*.json\""))
  
)


```

## Define Tool Object and Push to Platform {.tabset .tabset-fade .tabset-tabs}
  
### Tool object

```{r 5 create tool object, eval=run.mode=="push"}

tool <- Tool(
id = "genotype-check", 
label = "compare bam genotypes",
hints = requirements(docker(pull = "cgrlab/cgpbox_dev:develop"), cpu(1), mem(1000)),
baseCommand = "compareBamGenotypes.pl -o genotype_check -j genotype_check/genotype_check_result.json",
stdout = "std.out",
inputs = inputs,
outputs = outputs)


```

### Push app to sbg platform

```{r 6 push app to sbg, eval=destination=="platform"}

p$app_add("genotype-check", tool)


```

