
```{r include = FALSE}
require(rmarkdown); require(knitr); require(sevenbridges); require(readr)

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("~/sbg_auth.R")

```

<hr>

Extract reference files

## base command

```{sh base command, eval=FALSE}

mkdir extraced && tar -xvf [file] -C extracted


```

<br><br><br><br>

## docker 

The docker conatiner is

``` cgrlab/cgpbox_dev:develop ```

## arguments

## arguments

```{r arguments, eval=run.mode=="skip"}
arguments = list(value = "extracted", prefix = "-C")



```
## App ports {.tabset .tabset-fade .tabset-tabs}

### Inputs

Need to add more inputs here.

```{r inputs, eval=run.mode=="push"}
inputs = list(
  
input(id = "tar_file", label = "tar_file", description = "tar_file", type = "File", position = 1)

)

```

### Outputs

```{r output, eval = run.mode=="push"}

outputs = list(

output(id = "std_out", label = "std_out", 
description = "standard output", type = "File...",
metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"*.{out}\"")),
  
output(id = "extracted_files", label = "extracted_files", 
description = "extracted_files", type = "File...", 
metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"extracted/cgpbox_ref_2/*\""))
  
)


```

## Define Tool Object and Push to Platform {.tabset .tabset-fade .tabset-tabs}
  
### Tool object

```{r 5 create tool object, eval=run.mode=="push"}


tool <- Tool(
id = "tar_extract",
label = "tar_extract",
hints = requirements(docker(pull = "cgrlab/cgpbox_dev:develop"), cpu(1), mem(1000)),
baseCommand = "mkdir extracted && tar -xvf",
stdout = "std.out",
inputs = inputs,
arguments = CCBList(CommandLineBinding(position = 2, prefix = "-C", valueFrom = list("\"extracted\""))),
outputs = outputs
)


```

### Push app to sbg platform

```{r 6 push app to sbg, eval=destination=="platform"}

p$app_add("tar_extract", tool)


```

