```{r include = FALSE}
require(rmarkdown); require(knitr); require(sevenbridges); require(readr)

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("~/sbg_auth.R")

```

<hr>

First step in the cgpbox pipeline.  Generates useful stats on the wildtype and mutant tumour bams that will be used in the pipeline.

## base command

```
#if normal

verifyBamHomChk.pl 
-d 25
-o /datastore/output/$NAME_WT/contamination
-b $BAM_WT_TMP
-j /datastore/output/$NAME_WT/contamination/result.json

#if tumor

verifyBamHomChk.pl 
-d 25
-o /datastore/output/$NAME_MT/contamination
-b $BAM_MT_TMP
-a /datastore/output/${NAME_MT}_vs_${NAME_WT}/ascat/${NAME_MT}.copynumber.caveman.csv
-j /datastore/output/$NAME_MT/contamination/result.json

```

```{sh base command, eval=FALSE}

verifyBamHomChk.pl
-b [bam file]
-a [option input - from ASCAT - called copynumber.caveman.csv] 
-d 25
-o ./
-j result.json

```

<br><br><br><br>

## docker 

The docker conatiner is

``` cgrlab/cgpbox_dev:develop ```

## App ports {.tabset .tabset-fade .tabset-tabs}

### Inputs

```{r inputs, eval=run.mode=="push"}
inputs = list(
  
input(id = "bam", label = "bam", description = "either normal wildtype or tumour mutatantbam", type = "File", prefix = "-b", secondaryFiles = list(".bai")),

input(id = "adjusted_copynumber_csv", label = "adjusted_copynumber_csv", description = "adjusted for caveman copynumber csv", type = "File", prefix = "-a")

)

```

### Outputs

```{r output, eval = run.mode=="push"}

outputs = list(

output(id = "std_out", label = "std_out", 
description = "standard output", type = "File...",
metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"*.{out}\"")),
  
output(id = "verify_bam_result", label = "verify_bam_results", 
description = "verify bam results", type = "File",
inheritMetadataFrom = "#bam", metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"result.json\""))
  
)


```

## Define Tool Object and Push to Platform {.tabset .tabset-fade .tabset-tabs}
  
### Tool object

```{r 5 create tool object, eval=run.mode=="push"}

tool <- Tool(
id = "verify_bam", 
label = "verify_bams",
hints = requirements(docker(pull = "cgrlab/cgpbox_dev:develop"), cpu(1), mem(1000)),
baseCommand = "verifyBamHomChk.pl -d 25 -o ./ -j verify_bam_result.json",
stdout = "std.out",
inputs = inputs,
outputs = outputs)


```

### Push app to sbg platform

```{r 6 push app to sbg, eval=destination=="platform"}

p$app_add("verify_bams", tool)


```

