
```{r include = FALSE}
require(rmarkdown); require(knitr); require(sevenbridges); require(readr)

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("~/sbg_auth.R")

```

<hr>

Breakpoints via assembly - Identifies breaks and attempts to assemble rearrangements.

https://github.com/cancerit/BRASS

## base command

```{sh base command, eval=FALSE}

CPU=`grep -c ^processor /proc/cpuinfo` && # I want to use rabix to get CPU
brass.pl 
-t [tumour bam]
-n [normal wildtype bam]
-g [genome reference]
-ss [ascat *.samplestatistics.txt array]
-j 4 
-k 4 
-c $CPU
-s HUMAN 
-as GRCh37 
-pr WGS
-pl ILLUMINA
-d brass-ucscHiDepth_0.01_mrg1000_no_exon_coreChrs.bed.gz
-f brass-brass_np.groups.gz
-g_cache vagrent_Homo_sapiens.GRCh37.75.vagrent.cache.gz
-vi brass-viral.1.1.genomic.fa
-mi brass-all_ncbi_bacteria.20150703
-b brass-hs37d5_500bp_windows.gc.bed.gz
-ct brass-Human.GRCh37.CentTelo.tsv
-o ./brass_output
```

<br><br><br><br>

## docker 

The docker conatiner is

``` cgrlab/cgpbox_dev:develop ```

## arguments

No additional arguments

## App ports {.tabset .tabset-fade .tabset-tabs}

### Inputs

Need to add more inputs here.

```{r inputs, eval=run.mode=="push"}
inputs = list(
  
input(id = "tumour_bam", label = "tumour_bam", description = "tumour bam", type = "File", prefix = "-t"),

input(id = "normal_bam", label = "normal_bam", description = "wildtype bam", type = "File", prefix = "-n"),

input(id = "genome_reference", label = "genome_reference", description = "genome_reference", type = "File", prefix = "-g"),
  
input(id = "ascat_sample_statistics", label = "ascat_sample_statistics", description = "ascat_sample_statistics", type = "File...", prefix = "-ss"),
  
input(id = "cgpbox_reference_files", label = "cgpbox_reference_files", description = "extracted reference files", type = "File...", stageInput = "link")
  
)

```

### Outputs

```{r output, eval = run.mode=="push"}

outputs = list(

output(id = "std_out", label = "std_out", 
description = "standard output", type = "File...",
metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"*.{out}\"")),
  
output(id = "brass_output", label = "brass_output", 
description = "brass_output", type = "File...",
inheritMetadataFrom = "#normal_bam", metadata = list(org = "cgp"),
glob = Expression(engine = "#cwl-js-engine",
script = "\"brass_output/*\""))
  
)


```

## Define Tool Object and Push to Platform {.tabset .tabset-fade .tabset-tabs}
  
### Tool object

```{r 5 create tool object, eval=run.mode=="push"}

tool <- Tool(
id = "BRASS", 
label = "BRASS",
hints = requirements(docker(pull = "cgrlab/cgpbox_dev:develop"), cpu(1), mem(1000)),
baseCommand = "mkdir brass_output && CPU=`grep -c ^processor /proc/cpuinfo` && brass.pl -j 4 -k 4 -c $CPU -s HUMAN -as GRCh37 -pr WGS -pl ILLUMINA -d brass-ucscHiDepth_0.01_mrg1000_no_exon_coreChrs.bed.gz -f brass-brass_np.groups.gz -g_cache vagrent_Homo_sapiens.GRCh37.75.vagrent.cache.gz -vi brass-viral.1.1.genomic.fa -mi brass-all_ncbi_bacteria.20150703 -b brass-hs37d5_500bp_windows.gc.bed.gz -ct brass-Human.GRCh37.CentTelo.tsv -o ./brass_output",
stdout = "std.out",
inputs = inputs,
outputs = outputs)


```

### Push app to sbg platform

```{r 6 push app to sbg, eval=destination=="platform"}

p$app_add("BRASS", tool)


```

